//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceClient.FinanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/PersonalFinance")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ac_balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ac_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ac_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ac_typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ac_balance {
            get {
                return this.ac_balanceField;
            }
            set {
                if ((this.ac_balanceField.Equals(value) != true)) {
                    this.ac_balanceField = value;
                    this.RaisePropertyChanged("ac_balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ac_id {
            get {
                return this.ac_idField;
            }
            set {
                if ((this.ac_idField.Equals(value) != true)) {
                    this.ac_idField = value;
                    this.RaisePropertyChanged("ac_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ac_name {
            get {
                return this.ac_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.ac_nameField, value) != true)) {
                    this.ac_nameField = value;
                    this.RaisePropertyChanged("ac_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ac_type {
            get {
                return this.ac_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.ac_typeField, value) != true)) {
                    this.ac_typeField = value;
                    this.RaisePropertyChanged("ac_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/PersonalFinance")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ac_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal reqAmtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ac_id {
            get {
                return this.ac_idField;
            }
            set {
                if ((this.ac_idField.Equals(value) != true)) {
                    this.ac_idField = value;
                    this.RaisePropertyChanged("ac_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((this.c_idField.Equals(value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_name {
            get {
                return this.c_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.c_nameField, value) != true)) {
                    this.c_nameField = value;
                    this.RaisePropertyChanged("c_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal reqAmt {
            get {
                return this.reqAmtField;
            }
            set {
                if ((this.reqAmtField.Equals(value) != true)) {
                    this.reqAmtField = value;
                    this.RaisePropertyChanged("reqAmt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/PersonalFinance")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExpenceIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ac_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int t_amtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime t_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int t_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExpenceIncome {
            get {
                return this.ExpenceIncomeField;
            }
            set {
                if ((this.ExpenceIncomeField.Equals(value) != true)) {
                    this.ExpenceIncomeField = value;
                    this.RaisePropertyChanged("ExpenceIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ac_id {
            get {
                return this.ac_idField;
            }
            set {
                if ((this.ac_idField.Equals(value) != true)) {
                    this.ac_idField = value;
                    this.RaisePropertyChanged("ac_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((this.c_idField.Equals(value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int t_amt {
            get {
                return this.t_amtField;
            }
            set {
                if ((this.t_amtField.Equals(value) != true)) {
                    this.t_amtField = value;
                    this.RaisePropertyChanged("t_amt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime t_date {
            get {
                return this.t_dateField;
            }
            set {
                if ((this.t_dateField.Equals(value) != true)) {
                    this.t_dateField = value;
                    this.RaisePropertyChanged("t_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int t_id {
            get {
                return this.t_idField;
            }
            set {
                if ((this.t_idField.Equals(value) != true)) {
                    this.t_idField = value;
                    this.RaisePropertyChanged("t_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinanceService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        PersonalFinanceClient.FinanceService.Account CreateAccount(PersonalFinanceClient.FinanceService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Account> CreateAccountAsync(PersonalFinanceClient.FinanceService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccount", ReplyAction="http://tempuri.org/IService1/GetAccountResponse")]
        PersonalFinanceClient.FinanceService.Account GetAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccount", ReplyAction="http://tempuri.org/IService1/GetAccountResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Account> GetAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAccount", ReplyAction="http://tempuri.org/IService1/UpdateAccountResponse")]
        PersonalFinanceClient.FinanceService.Account UpdateAccount(PersonalFinanceClient.FinanceService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAccount", ReplyAction="http://tempuri.org/IService1/UpdateAccountResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Account> UpdateAccountAsync(PersonalFinanceClient.FinanceService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAccount", ReplyAction="http://tempuri.org/IService1/DeleteAccountResponse")]
        void DeleteAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAccount", ReplyAction="http://tempuri.org/IService1/DeleteAccountResponse")]
        System.Threading.Tasks.Task DeleteAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCategories", ReplyAction="http://tempuri.org/IService1/GetAllCategoriesResponse")]
        PersonalFinanceClient.FinanceService.Category[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCategories", ReplyAction="http://tempuri.org/IService1/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoriesByAccountId", ReplyAction="http://tempuri.org/IService1/GetCategoriesByAccountIdResponse")]
        PersonalFinanceClient.FinanceService.Category[] GetCategoriesByAccountId(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoriesByAccountId", ReplyAction="http://tempuri.org/IService1/GetCategoriesByAccountIdResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category[]> GetCategoriesByAccountIdAsync(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategory", ReplyAction="http://tempuri.org/IService1/AddCategoryResponse")]
        PersonalFinanceClient.FinanceService.Category AddCategory(PersonalFinanceClient.FinanceService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategory", ReplyAction="http://tempuri.org/IService1/AddCategoryResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category> AddCategoryAsync(PersonalFinanceClient.FinanceService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategory", ReplyAction="http://tempuri.org/IService1/UpdateCategoryResponse")]
        PersonalFinanceClient.FinanceService.Category UpdateCategory(PersonalFinanceClient.FinanceService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategory", ReplyAction="http://tempuri.org/IService1/UpdateCategoryResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category> UpdateCategoryAsync(PersonalFinanceClient.FinanceService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        void DeleteCategory(int c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        System.Threading.Tasks.Task DeleteCategoryAsync(int c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTransaction", ReplyAction="http://tempuri.org/IService1/AddTransactionResponse")]
        PersonalFinanceClient.FinanceService.Transaction AddTransaction(PersonalFinanceClient.FinanceService.Transaction transaction, bool isExpence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTransaction", ReplyAction="http://tempuri.org/IService1/AddTransactionResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Transaction> AddTransactionAsync(PersonalFinanceClient.FinanceService.Transaction transaction, bool isExpence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTransactions", ReplyAction="http://tempuri.org/IService1/GetAllTransactionsResponse")]
        PersonalFinanceClient.FinanceService.Transaction[] GetAllTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTransactions", ReplyAction="http://tempuri.org/IService1/GetAllTransactionsResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Transaction[]> GetAllTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionsByAccountId", ReplyAction="http://tempuri.org/IService1/GetTransactionsByAccountIdResponse")]
        PersonalFinanceClient.FinanceService.Transaction[] GetTransactionsByAccountId(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionsByAccountId", ReplyAction="http://tempuri.org/IService1/GetTransactionsByAccountIdResponse")]
        System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Transaction[]> GetTransactionsByAccountIdAsync(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTransaction", ReplyAction="http://tempuri.org/IService1/DeleteTransactionResponse")]
        void DeleteTransaction(int t_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTransaction", ReplyAction="http://tempuri.org/IService1/DeleteTransactionResponse")]
        System.Threading.Tasks.Task DeleteTransactionAsync(int t_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PersonalFinanceClient.FinanceService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PersonalFinanceClient.FinanceService.IService1>, PersonalFinanceClient.FinanceService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PersonalFinanceClient.FinanceService.Account CreateAccount(PersonalFinanceClient.FinanceService.Account account) {
            return base.Channel.CreateAccount(account);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Account> CreateAccountAsync(PersonalFinanceClient.FinanceService.Account account) {
            return base.Channel.CreateAccountAsync(account);
        }
        
        public PersonalFinanceClient.FinanceService.Account GetAccount(int id) {
            return base.Channel.GetAccount(id);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Account> GetAccountAsync(int id) {
            return base.Channel.GetAccountAsync(id);
        }
        
        public PersonalFinanceClient.FinanceService.Account UpdateAccount(PersonalFinanceClient.FinanceService.Account account) {
            return base.Channel.UpdateAccount(account);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Account> UpdateAccountAsync(PersonalFinanceClient.FinanceService.Account account) {
            return base.Channel.UpdateAccountAsync(account);
        }
        
        public void DeleteAccount(int id) {
            base.Channel.DeleteAccount(id);
        }
        
        public System.Threading.Tasks.Task DeleteAccountAsync(int id) {
            return base.Channel.DeleteAccountAsync(id);
        }
        
        public PersonalFinanceClient.FinanceService.Category[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public PersonalFinanceClient.FinanceService.Category[] GetCategoriesByAccountId(int accountId) {
            return base.Channel.GetCategoriesByAccountId(accountId);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category[]> GetCategoriesByAccountIdAsync(int accountId) {
            return base.Channel.GetCategoriesByAccountIdAsync(accountId);
        }
        
        public PersonalFinanceClient.FinanceService.Category AddCategory(PersonalFinanceClient.FinanceService.Category category) {
            return base.Channel.AddCategory(category);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category> AddCategoryAsync(PersonalFinanceClient.FinanceService.Category category) {
            return base.Channel.AddCategoryAsync(category);
        }
        
        public PersonalFinanceClient.FinanceService.Category UpdateCategory(PersonalFinanceClient.FinanceService.Category category) {
            return base.Channel.UpdateCategory(category);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Category> UpdateCategoryAsync(PersonalFinanceClient.FinanceService.Category category) {
            return base.Channel.UpdateCategoryAsync(category);
        }
        
        public void DeleteCategory(int c_id) {
            base.Channel.DeleteCategory(c_id);
        }
        
        public System.Threading.Tasks.Task DeleteCategoryAsync(int c_id) {
            return base.Channel.DeleteCategoryAsync(c_id);
        }
        
        public PersonalFinanceClient.FinanceService.Transaction AddTransaction(PersonalFinanceClient.FinanceService.Transaction transaction, bool isExpence) {
            return base.Channel.AddTransaction(transaction, isExpence);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Transaction> AddTransactionAsync(PersonalFinanceClient.FinanceService.Transaction transaction, bool isExpence) {
            return base.Channel.AddTransactionAsync(transaction, isExpence);
        }
        
        public PersonalFinanceClient.FinanceService.Transaction[] GetAllTransactions() {
            return base.Channel.GetAllTransactions();
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Transaction[]> GetAllTransactionsAsync() {
            return base.Channel.GetAllTransactionsAsync();
        }
        
        public PersonalFinanceClient.FinanceService.Transaction[] GetTransactionsByAccountId(int accountId) {
            return base.Channel.GetTransactionsByAccountId(accountId);
        }
        
        public System.Threading.Tasks.Task<PersonalFinanceClient.FinanceService.Transaction[]> GetTransactionsByAccountIdAsync(int accountId) {
            return base.Channel.GetTransactionsByAccountIdAsync(accountId);
        }
        
        public void DeleteTransaction(int t_id) {
            base.Channel.DeleteTransaction(t_id);
        }
        
        public System.Threading.Tasks.Task DeleteTransactionAsync(int t_id) {
            return base.Channel.DeleteTransactionAsync(t_id);
        }
    }
}
